name: Test FirestoreExample

on: push

defaults:
  run:
    working-directory: Example

jobs:
  test:
    name: "Test FirestoreExample"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable  
      - name: Cache SwiftPM
        uses: actions/cache@v2
        with:
            path: SourcePackages
            key: ${{ runner.os }}-spm-${{ hashFiles('*.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
            restore-keys: ${{ runner.os }}-spm- 
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Test
        run: |
          xcodebuild -scheme FirestoreExample \
          build -destination "name=iPhone 12" \
          -clonedSourcePackagesDirPath SourcePackages \
          | xcpretty
