name: Test Source

on: push

jobs:
  test:
    name: "Test Source"
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable  
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Test
        run: xcodebuild -scheme EasyFirebaseSwift build -destination "name=iPhone 12" | xcpretty
